import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Menu from "../components/Menu";

const inter = Inter({ subsets: ["latin"] });

export default function Test() {
  return (
    <>
      <Head>
        <title>Hello, word!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Menu />
          <div className={styles.contents}>
            <div className={styles.leftSide} />
            <div className={styles.dividingLine} />
            <div className={styles.rightSide}>
              <div className={styles.inputPart}>
                <p className={styles.loginContent}>Test Page</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
